# ----
# Site

title: Al-Aqssa
url: "https://aqssa.net/"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
snipcart_key: "NWNjOWZhYjctYmE1ZS00MDM3LThkNjUtZmE5M2NiMTU1NzAwNjM2MjYzNTE1MzM5ODg1ODkw"
snipcart_currency: "usd"

logo: /siteicon.png
description: Al-Aqssa
author:
  name: Al-Aqssa
  email: kareem@aqssa.net
  phone: "+971508557671"
social:
  name: Fur Template
  links:
    - https://github.com/CloudCannon/fur-jekyll-template

# -----
# Build
timezone: Etc/UTC

collections:
  staff_members:
    output: false
  products:
    output: true

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

social_icons:
  - Email
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
